config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'about_us', to: 'pages#about_us'
  get 'contact', to: 'pages#contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :about_us, :contact]

  def home
  end

  def about_us
  end

  def contact
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head><%= favicon_link_tag 'Aschenbrenner_favicon.ico' %>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Aschenbrenner Group | Real Estate & Investment</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/about_us.html.erb
<%= render 'shared/navbar' %>
<div class="about-banner">
	<div class="about-wrapper">
		<%= image_tag "about_us_strip.png", class: "about-strip hidden-md hidden-sm hidden-xs" %>
		<%= image_tag "about_us_strip_small.png", class: "about-strip hidden-xl hidden-lg hidden-xs" %>
		<%= image_tag "about_us_strip_v_small.png", class: "about-strip hidden-xl hidden-lg hidden-md hidden-sm" %>
		<div class="about-content">
			<h4><strong>Aschenbrenner Group is an international private real estate and investment company founded by Klaus Aschenbrenner.</strong><br></br>
			We strive for excellence in all we do and this is reflected in the long relationships we have with our clients. We are focussed on real estate and investment opportunities around Europe and
 -			the rest of the world
			We are focussed on real estate and investment opportunities around Europe and the world, all benefitting from our experience, expertise and broad range of resources. <br></br>
			We tend to invest in areas in which we have deep experience: real estate and investment.
			Our mission is simple: <br></br><span>Our Clients are in the heart of our values.</span></h4>
	  </div>
    <div class="circles">
	  	<div class="about-us-circle-1">
	  		<%= image_tag "about_us_circle1.png", class: "circle1" %>
	  		<p><%= image_tag "real_estate.png", class: "real-estate-title" %>Aschenbrenner Group operates globally and invests locally, in Europe and around the world.</p>
	  	</div>
	  	<div class="about-us-circle-2">
	  		<%= image_tag "about_us_circle2.png", class: "circle2" %>
	  		<p><%= image_tag "investment.png", class: "investment-title" %>With a strong knowledge of the market and experience of the economic cycles of the past 30 years, we invest with the right vision in the international real estate markets.</p>
	  	</div>
    </div>
	</div>
</div>

app/views/pages/contact.html.erb
<%= render 'shared/navbar' %>
<div class="contact-banner">
	<div class="contact-wrapper">
		<%= image_tag "contact_us_strip.png", class: "about-strip hidden-md hidden-sm hidden-xs" %>
        <%= image_tag "contact_us_strip_small.png", class: "about-strip hidden-xl hidden-lg hidden-xs" %>
        <%= image_tag "contact_us_strip_v_small.png", class: "about-strip hidden-xl hidden-lg hidden-md hidden-sm" %>
		<div class="contact-content">
			<div class="contact-address">
				<h4><strong>Aschenbrenner Group Ltd<br></br>
				Level 1, Devonshire House<br>
				One Mayfair Place<br>
				Mayfair<br>
				London W1J 8AJ<br>
				United Kingdom</strong></h4>
			</div>
			<div class="contact-details">
				<p><%= image_tag "globe.png", class: "globe" %><a href="mailto:info@aschenbrenner-group.com">info@aschenbrenner-group.com</a></p>
				<p><%= image_tag "phone.png", class: "phone" %><a href="tel:+44-207-268-4965">T + 44 (0) 207 268 4965</a></p></div>
            <div id="map"></div>

<script>
  function initMap() {
    var aG = {lat: 51.507283, lng: -0.143041};
    var map = new google.maps.Map(document.getElementById('map'), {
      center: aG,
      zoom: 17,
      styles: [
    {
        "featureType": "administrative",
        "elementType": "labels.text.fill",
        "stylers": [
            {
                "color": "#444444"
            }
        ]
    },
    {
        "featureType": "landscape",
        "elementType": "all",
        "stylers": [
            {
                "color": "#f2f2f2"
            }
        ]
    },
    {
        "featureType": "poi",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "road",
        "elementType": "all",
        "stylers": [
            {
                "saturation": -100
            },
            {
                "lightness": 45
            }
        ]
    },
    {
        "featureType": "road.highway",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "simplified"
            }
        ]
    },
    {
        "featureType": "road.arterial",
        "elementType": "labels.icon",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "transit",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "off"
            },
            {
                "hue": "#ff0000"
            }
        ]
    },
    {
        "featureType": "water",
        "elementType": "all",
        "stylers": [
            {
                "color": "#ffffff"
            },
            {
                "visibility": "on"
            }
        ]
    },
    {
        "featureType": "water",
        "elementType": "labels.text.fill",
        "stylers": [
            {
                "hue": "#ff0000"
            }
        ]
    }
],
      maxZoom: 17,
      minZoom: 17,
      zoomControl: false,
      streetViewControl: false,
      gestureHandling: 'none'
    });
    var marker = new google.maps.Marker({
      position: aG,
      map: map,
      icon: { url: "assets/triangle.png" }
    });
    var transitLayer = new google.maps.TransitLayer();
    transitLayer.setMap(map);
  }
</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAXYSD4yxb7odB5Z_m4L7atqgCn8E0nwP0&callback=initMap">
</script>
		</div>
    </div>


</div>

app/views/pages/home.html.erb
<%= render 'shared/landing_navbar' %>
<div class="banner wrapper">
	<div class="banner-content hidden-md hidden-sm hidden-xs">
		<%= image_tag "Aschenbrenner_logo_main.png", class: "landing-logo" %>
	    <%= image_tag "Aschenbrenner_strapline.png", class: "landing-strapline" %>
  	</div>
  	<div class="banner-content hidden-xl hidden-lg">
		<%= image_tag "Aschenbrenner_logo_main_small.png", class: "landing-logo" %>
	    <%= image_tag "Aschenbrenner_strapline.png", class: "landing-strapline" %>
  	</div>
  	<div class="faded-logo fadeIn hidden hidden-xs hidden-sm">
    <%= image_tag "http://res.cloudinary.com/dqxvcdy6w/image/upload/v1504597182/Asset_9_1_aof9tg.png" %>
  	</div>
	<div class="home-strip fadeIn hidden hidden-sm hidden-xs text-center">
		<h4 class="hidden">Real Estate & Investment</h4>
	</div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_landing_navbar.html.erb
<div class="navbar-landing-abg">

    <!-- Logo -->
    <%= link_to root_path, class: "navbar-landing-abg-brand" do %>
      <!-- <%= image_tag "landing-abg_Recruitment_Nav_Logo.png", class: "navbar-landing-abg-submark" %> -->
    <% end %>

    <!-- Right Navigation -->
    <div class="navbar-landing-abg-right hidden-xs hidden-sm">
        <h5><%= link_to "About Us", about_us_path %></h5>
        <h5><%= link_to "Contact", contact_path %></h5>
        <!-- <div class="navbar-sm">
          <%= link_to "https://www.instagram.com", target: "_blank" do %>
            <i class="fa fa-instagram"></i>
          <% end %>
          <%= link_to "https://twitter.com", target: "_blank" do %>
            <i class="fa fa-twitter"></i>
          <% end %>
          <%= link_to "https://www.linkedin.com/in", target: "_blank" do %>
            <i class="fa fa-linkedin"></i>
          <% end %>
        </div> -->
    </div>

    <!-- Dropdown list appearing on mobile only -->
    <div class="navbar-landing-abg-item hidden-md hidden-lg">
    <!-- Social Media mobile only -->
      <!-- <div class="navbar-sm-mob">
        <%= link_to "https://www.instagram.com", target: "_blank" do %>
          <i class="fa fa-instagram"></i>
        <% end %>
        <%= link_to "https://twitter.com", target: "_blank" do %>
          <i class="fa fa-twitter"></i>
        <% end %>
        <%= link_to "https://www.linkedin.com/", target: "_blank" do %>
          <i class="fa fa-linkedin"></i>
        <% end %>
      </div> -->
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle toggle-yellow" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-landing-abg-dropdown-menu">
          <li><%= link_to "About Us", about_us_path %></li>
          <li><%= link_to "Contact", contact_path %></li>
        </ul>
      </div>
    </div>
  </div>

app/views/shared/_navbar.html.erb
<div class="navbar-abg">

    <!-- Logo -->
    <%= link_to root_path, class: "navbar-abg-brand" do %>
      <%= image_tag "Logo.png", class: "navbar-abg-submark" %>
    <% end %>

    <!-- Right Navigation -->
    <div class="navbar-abg-right hidden-xs hidden-sm">
        <h5><%= link_to "About Us", about_us_path, class: "about-link" %></h5>
        <h5><%= link_to "Contact", contact_path, class: "contact-link" %></h5>
        <!-- <div class="navbar-sm">
          <%# link_to "https://www.instagram.com", target: "_blank" do %>
            <i class="fa fa-instagram"></i>
          <%# end %>
          <%# link_to "https://twitter.com", target: "_blank" do %>
            <i class="fa fa-twitter"></i>
          <%# end %>
          <%# link_to "https://www.linkedin.com/in", target: "_blank" do %>
            <i class="fa fa-linkedin"></i>
          <%# end %>
        </div> -->
    </div>

    <!-- Dropdown list appearing on mobile only -->
    <div class="navbar-abg-item hidden-md hidden-lg">
    <!-- Social Media mobile only -->
      <!-- <div class="navbar-sm-mob">
        <%= link_to "https://www.instagram.com", target: "_blank" do %>
          <i class="fa fa-instagram"></i>
        <% end %>
        <%= link_to "https://twitter.com", target: "_blank" do %>
          <i class="fa fa-twitter"></i>
        <% end %>
        <%= link_to "https://www.linkedin.com/", target: "_blank" do %>
          <i class="fa fa-linkedin"></i>
        <% end %>
      </div> -->
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle toggle-yellow" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-abg-dropdown-menu">
          <li><%= link_to "About Us", about_us_path %></li>
          <li><%= link_to "Contact", contact_path %></li>
        </ul>
      </div>
    </div>
  </div>